public class funcsContent {

    @org.hibernate.validator.constraints.NotEmpty
    public void build() throws Exception {
      io.github.benas.todolist.web.action.todo.TodoAction clazz23 = new io.github.benas.todolist.web.action.todo.TodoAction();
clazz23.setUpload();
clazz23.setUploadContentType();
clazz23.setUploadFileName();
clazz23.execute();
clazz23.create();
clazz23.upload();
clazz23.doCreate();
clazz23.doUpload();
clazz23.update();
clazz23.doUpdate();
clazz23.doDelete();
clazz23.getTodo();
clazz23.getError();
clazz23.setTodo();
clazz23.setTodoId();
io.github.benas.todolist.web.action.IndexAction clazz344 = new io.github.benas.todolist.web.action.IndexAction();
io.github.benas.todolist.web.action.user.AccountAction clazz420 = new io.github.benas.todolist.web.action.user.AccountAction();
clazz420.account();
clazz420.register();
clazz420.doRegister();
clazz420.isAlreadyUsed();
clazz420.validateRegistrationForm();
clazz420.checkPasswordsMatch();
clazz420.confirmationPasswordDoesNotMatchPassword();
clazz420.validateConfirmationPassword();
clazz420.validatePassword();
clazz420.validateEmail();
clazz420.validateName();
clazz420.doUpdate();
clazz420.isDifferent();
clazz420.doDelete();
clazz420.invalidateSession();
clazz420.doChangePassword();
clazz420.newPasswordDoesNotMatchConfirmationPassword();
clazz420.incorrectCurrentPassword();
clazz420.validateChangePasswordForm();
clazz420.validateConfirmPassword();
clazz420.validateNewPassword();
clazz420.validateCurrentPassword();
clazz420.getRegisterTabStyle();
clazz420.getChangePasswordForm();
clazz420.getRegistrationForm();
clazz420.getUser();
clazz420.getError();
clazz420.getErrorName();
clazz420.getErrorEmail();
clazz420.getErrorPassword();
clazz420.getErrorNewPassword();
clazz420.getErrorConfirmationPassword();
clazz420.getErrorConfirmationPasswordMatching();
clazz420.getUpdateProfileSuccessMessage();
clazz420.getUpdatePasswordSuccessMessage();
clazz420.getErrorCurrentPassword();
clazz420.setChangePasswordForm();
clazz420.setRegistrationForm();
clazz420.setUser();
io.github.todolist.core.repository.api.UserRepository clazz1360 = new io.github.todolist.core.repository.api.UserRepository();
clazz1360.getUserByEmail();
clazz1360.login();
clazz1360.create();
clazz1360.update();
clazz1360.remove();
io.github.benas.todolist.web.common.tags.StatusStyleTag clazz1414 = new io.github.benas.todolist.web.common.tags.StatusStyleTag();
clazz1414.doTag();
clazz1414.setStatus();
io.github.todolist.core.domain.Todo clazz1482 = new io.github.todolist.core.domain.Todo();
clazz1482.getOutput();
clazz1482.native2ascii();
clazz1482.getId();
clazz1482.getUserId();
clazz1482.setUserId();
clazz1482.getTitle();
clazz1482.setTitle();
clazz1482.isDone();
clazz1482.setDone();
clazz1482.getPriority();
clazz1482.setPriority();
clazz1482.getDueDate();
clazz1482.setDueDate();
clazz1482.toString();
io.github.todolist.core.service.api.TodoService clazz1912 = new io.github.todolist.core.service.api.TodoService();
clazz1912.getTodoById();
clazz1912.getTodoListByUser();
clazz1912.searchTodoListByTitle();
clazz1912.update();
clazz1912.create();
clazz1912.remove();
io.github.todolist.core.domain.User clazz1981 = new io.github.todolist.core.domain.User();
clazz1981.getId();
clazz1981.getName();
clazz1981.setName();
clazz1981.getEmail();
clazz1981.setEmail();
clazz1981.getPassword();
clazz1981.setPassword();
clazz1981.toString();
io.github.todolist.core.service.api.UserService clazz2168 = new io.github.todolist.core.service.api.UserService();
clazz2168.getUserByEmail();
clazz2168.login();
clazz2168.create();
clazz2168.update();
clazz2168.remove();
io.github.todolist.core.service.impl.TodoServiceImpl clazz2218 = new io.github.todolist.core.service.impl.TodoServiceImpl();
clazz2218.getTodoById();
clazz2218.getTodoListByUser();
clazz2218.searchTodoListByTitle();
clazz2218.update();
clazz2218.create();
clazz2218.remove();
io.github.benas.todolist.web.action.user.SessionAction clazz2339 = new io.github.benas.todolist.web.action.user.SessionAction();
clazz2339.login();
clazz2339.doLogin();
clazz2339.doLogout();
clazz2339.getLoginForm();
clazz2339.setLoginForm();
clazz2339.getLoginTabStyle();
clazz2339.getError();
io.github.todolist.core.domain.Priority clazz2514 = new io.github.todolist.core.domain.Priority();
io.github.benas.todolist.web.common.form.RegistrationForm clazz2548 = new io.github.benas.todolist.web.common.form.RegistrationForm();
clazz2548.getName();
clazz2548.setName();
clazz2548.getEmail();
clazz2548.setEmail();
clazz2548.getPassword();
clazz2548.setPassword();
clazz2548.getConfirmationPassword();
clazz2548.setConfirmationPassword();
io.github.benas.todolist.web.common.form.ChangePasswordForm clazz2705 = new io.github.benas.todolist.web.common.form.ChangePasswordForm();
clazz2705.getCurrentPassword();
clazz2705.setCurrentPassword();
clazz2705.getNewPassword();
clazz2705.setNewPassword();
clazz2705.getConfirmationPassword();
clazz2705.setConfirmationPassword();
io.github.benas.todolist.web.common.form.LoginForm clazz2835 = new io.github.benas.todolist.web.common.form.LoginForm();
clazz2835.getPassword();
clazz2835.setPassword();
clazz2835.getEmail();
clazz2835.setEmail();
io.github.todolist.core.repository.impl.UserRepositoryImpl clazz2923 = new io.github.todolist.core.repository.impl.UserRepositoryImpl();
clazz2923.create();
clazz2923.update();
clazz2923.remove();
clazz2923.getUserByEmail();
clazz2923.login();
io.github.benas.todolist.web.interceptor.LoginInterceptor clazz3093 = new io.github.benas.todolist.web.interceptor.LoginInterceptor();
clazz3093.intercept();
io.github.benas.todolist.web.common.tags.PriorityIconTag clazz3146 = new io.github.benas.todolist.web.common.tags.PriorityIconTag();
clazz3146.doTag();
clazz3146.setPriority();
io.github.benas.todolist.web.action.BaseAction clazz3198 = new io.github.benas.todolist.web.action.BaseAction();
clazz3198.prepare();
clazz3198.getSessionUser();
clazz3198.setTodoService();
clazz3198.setUserService();
io.github.benas.todolist.web.action.todo.SearchTodoAction clazz3285 = new io.github.benas.todolist.web.action.todo.SearchTodoAction();
clazz3285.execute();
clazz3285.getTitle();
clazz3285.getTodoList();
clazz3285.setTitle();
io.github.benas.todolist.web.common.util.TodoListUtils clazz3360 = new io.github.benas.todolist.web.common.util.TodoListUtils();
clazz3360.getPriorityIcon();
clazz3360.getStatusStyle();
clazz3360.getStatusLabel();
clazz3360.highlight();
clazz3360.countTotalDone();
io.github.todolist.core.repository.impl.TodoRepositoryImpl clazz3536 = new io.github.todolist.core.repository.impl.TodoRepositoryImpl();
clazz3536.getTodoById();
clazz3536.getTodoListByUser();
clazz3536.getTodoListByUserAndTitle();
clazz3536.update();
clazz3536.create();
clazz3536.remove();
io.github.todolist.core.service.impl.UserServiceImpl clazz3694 = new io.github.todolist.core.service.impl.UserServiceImpl();
clazz3694.create();
clazz3694.update();
clazz3694.remove();
clazz3694.getUserByEmail();
clazz3694.login();
io.github.todolist.core.repository.api.TodoRepository clazz3799 = new io.github.todolist.core.repository.api.TodoRepository();
clazz3799.getTodoById();
clazz3799.getTodoListByUser();
clazz3799.getTodoListByUserAndTitle();
clazz3799.create();
clazz3799.update();
clazz3799.remove();
io.github.benas.todolist.web.action.user.FilesAction clazz3860 = new io.github.benas.todolist.web.action.user.FilesAction();
clazz3860.execute();
clazz3860.getTodoList();
clazz3860.getHomeTabStyle();
clazz3860.getTotalCount();
clazz3860.getDoneCount();
clazz3860.getTodoCount();
io.github.benas.todolist.web.action.user.HomeAction clazz3989 = new io.github.benas.todolist.web.action.user.HomeAction();
clazz3989.execute();
clazz3989.getTodoList();
clazz3989.getHomeTabStyle();
clazz3989.getTotalCount();
clazz3989.getDoneCount();
clazz3989.getTodoCount();
io.github.benas.todolist.web.common.tags.StatusLabelTag clazz4120 = new io.github.benas.todolist.web.common.tags.StatusLabelTag();
clazz4120.doTag();
clazz4120.setStatus();
io.github.benas.todolist.web.common.tags.HighlightTag clazz4183 = new io.github.benas.todolist.web.common.tags.HighlightTag();
clazz4183.doTag();
clazz4183.doHighlight();
clazz4183.setPattern();
clazz4183.setCssClass();
clazz4183.setCaseSensitive();
io.github.benas.todolist.web.action.AboutAction clazz4326 = new io.github.benas.todolist.web.action.AboutAction();
clazz4326.getAboutTabStyle();
javax.validation.constraints.Size;
  javax.persistence.GeneratedValue;
  javax.persistence.NamedQueries;
  javax.persistence.Temporal;
  org.hibernate.validator.constraints.NotEmpty;
  org.hibernate.validator.constraints.Email;
  javax.persistence.PersistenceContext;
  org.springframework.transaction.annotation.Transactional;
  org.springframework.stereotype.Service;
  javax.persistence.Id;
  javax.persistence.Entity;
  javax.persistence.NamedQuery;
  javax.persistence.Override;
  org.springframework.stereotype.Repository;
  javax.persistence.Column;
  javax.persistence.Enumerated;
  org.springframework.beans.factory.annotation.Autowired;
    }
}
